name: "Comment on Issues with release version"
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: ""
        run: |
          echo "PR was merged!"
          echo "github.event.pull_request.number: ${{github.event.pull_request.number}}"
          echo "github.event.pull_request.issue_url: ${{github.event.pull_request.issue_url}}"
          echo "github.event.pull_request._links: ${{github.event.pull_request._links}}"
          echo "github.event.pull_request._links.issue: ${{github.event.pull_request._links.issue}}"
          echo "github.event.pull_request._links.issue.href: ${{github.event.pull_request._links.issue.href}}"
