name: "Pre-Release"
on:
  release:
    types: [prereleased]

jobs:
  pre_release_job:
    runs-on: ubuntu-latest
    steps:
      - name: testing pre-release action
        run: echo this is the pre-release action
      - name: tagName
        run: echo tag name is ${{github.ref_name}}
      - name: make zip
        run: zip -r AboveVTT-${{github.ref_name}}.zip .
