name: pre-release
run-name: ${{ github.actor }} is publishing a pre-release
on: [push]
jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install node-jq --save
      - run: |
          oldVersion=$(cat manifest.json | jq -r .version) && echo $oldVersion
          oldVersionName=$(cat manifest.json | jq -r .version_name) && echo $oldVersionName
          if [[ "$oldVersionName" = "$oldVersion"* ]];
          then
            echo "$oldVersionName starts with $oldVersion"
            betaNumber=${oldVersionName##*$oldVersion-beta}
            echo betaNumber: $betaNumber
            newBetaNumber=$((betaNumber+1))
            echo newBetaNumber: $newBetaNumber 
          else
            echo "$oldVersionName does not start with $oldVersion"
            echo "new version_name is ${oldVersion}-beta1"
          fi
