name: release-build
run-name: ${{ github.actor }} is publishing version ${{ inputs.version_name }}
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: prerelease or production?
        options:
          - prerelease
          - production
        default: prerelease
      prerelease:
        description: "Should this release be marked as a pre-release?"
        required: true
        default: true
      version_name:
        description: "Something like 0.84 or 0.84-beta2"
        required: true
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          author_name: github.actor
          author_email: github
      - name: "print choice variables"
        run: |
          echo ${{inputs.release_type}}
          echo ${{inputs.prerelease}}
          echo ${{inputs.version_name}}
          if [[ "${{inputs.release_type}}" == "production" ]]; then
            echo production build
          else
            echo prerelease build
          fi
      - name: "build zip"
        run: |
          git archive -o "AboveVTT-${{inputs.version_name}}.zip" HEAD
      - name: "publish release"
        run: |
          release_json=$(curl -X POST -H 'Authorization: Bearer ${{secrets.GITHUB_TOKEN}}' https://api.github.com/repos/${GITHUB_REPOSITORY}/releases -d '{"tag_name": "${{inputs.version_name}}","name":"${{inputs.version_name}}", "prerelease": true, "generate_release_notes": true }')
          echo successfully created release
          assets_url=$(echo $release_json | grep -o '"assets_url": "[^"]*' | grep -o '[^"]*$')
          echo assets_url: ${assets_url}
          echo "assets_url=${assets_url}" >> $GITHUB_ENV
      - name: "upload zip"
        run: |
          echo About to upload zip to ${{env.assets_url}}?name=AboveVTT-${{inputs.version_name}}.zip  
          curl -L \
            -X POST \
            -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}"\
            -H "Content-Type: application/octet-stream" \
            ${{env.assets_url}}?name=AboveVTT-${{inputs.version_name}}.zip \
            --data-binary "AboveVTT-${{inputs.version_name}}.zip"
