name: release-build
run-name: ${{ github.actor }} is publishing version ${{ inputs.version_name }}
on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: "Should this release be marked as a pre-release?"
        required: true
        default: true
      version_name:
        description: "Something like 0.84 or 0.84-beta2"
        required: true
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          author_name: github.actor
          author_email: github
      - name: "build zip"
        run: |
          git archive -o "AboveVTT-${{inputs.version_name}}.zip" HEAD
      - name: "publish release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{inputs.version_name}}"
          prerelease: ${{ inputs.prerelease }}
          title: "${{inputs.version_name}}"
          files: |
            *.zip
            LICENSE